import { Link } from 'react-router-dom';
import LearningLayout, { CourseEnquiry } from '../components/learning/LearningLayout';
import { offerings, teachingFields } from '../data/learning';

export default function TeachingFields() {
  return <LearningLayout title="Teaching fields & specialists" intro="Eight teaching fields support one shared curriculum. Contributors may teach, co-facilitate or review material; one person may cover several fields where their competence supports it.">
    <p>This is a proposed staffing map, not a verified list of legal qualification requirements or an announcement of appointed teachers.</p>
    <section className="learning-section"><h2>Specialist roles</h2><div className="learning-grid">{teachingFields.map(field => <article className="learning-card learning-section" id={`field-${field.id}`} key={field.id}><h3>{field.id}. {field.name}</h3><p>{field.content}</p><p><strong>Suitable specialist:</strong> {field.specialist}</p><p><strong>Contribution:</strong> {field.role}</p><details><summary>Related sessions and programmes</summary><ul>{offerings.filter(course => course.fields.includes(field.id)).map(course => <li key={course.slug}><Link to={`/learning/${course.slug}`}>{course.title}</Link></li>)}</ul></details></article>)}</div></section>
    <section className="learning-panel"><h2>A manageable founding team</h2><ul><li><strong>Project and creative lead:</strong> Psy Elf’s proposed teaching focus is framework orientation, rhythm, music, creative event planning and coordination, drawing on DJ and event-production experience.</li><li><strong>Adult educator/community facilitator:</strong> curriculum, inclusion, group learning and observed teaching practice.</li><li><strong>Garden/ecology educator:</strong> Living Garden and outdoor learning.</li><li><strong>Research/content reviewer:</strong> source provenance, historical context and evidence.</li></ul><p>Add movement teachers, mediators and other guests when their modules are scheduled. These are proposed responsibilities; availability and appointments remain unconfirmed.</p></section>
    <section className="learning-panel"><h2>Teaching standards and scope</h2><p>Contributors should provide relevant experience, a sample lesson, references, a clear scope of competence and an accessible teaching approach. Reviewers record what they checked and what remains uncertain.</p><p>For local First Nations knowledge, invite appropriate community-authorised contributors to determine what they wish to teach and how it is credited and paid.</p><p>Electrical systems, construction, fire performance, medicinal plants and intensive breathwork remain outside this introductory programme until appropriate expertise and delivery arrangements are in place.</p><p>Keep historical sources, modern project interpretations, proposals and scientific evidence distinct. Symbolism supports reflection; it does not establish hidden events or guaranteed outcomes.</p></section>
    <CourseEnquiry title="teaching, co-facilitation or content review" />
  </LearningLayout>;
}
